### ISSUE TITLE
Hovering in dark mode

### ISSUE THREAD

**Issue by chept** [kookma/TW-Trashbin#10]
The background color for an hovered item in the bin doesn't adapt to dark modes.
Using a defined palette variable could be better.

For example I am using CupertinoDark palette and do:
`.kk-trashbin-row:hover { background-color: <<colour pre-background>>; }`

looks good in almost every default palettes.

**Comment by kookma** [comment]
Good catch, thank you! I will push a patch.

**Comment by kookma** [comment]
Implemented in Trashbin 1.3.1
