### ISSUE TITLE
Instructions for Trashbin plugin

### ISSUE THREAD

**Issue by dhjackal** [kookma/TW-Trashbin#12]
Hi Mohammad, 

Just cycling through the plugins I use for my wiki. The Trashbin has been in my arsenal for some time now. Thanks for the plugin.....really is a vital resource. A couple of things....the instructions on customisation of the buttons on the tiddler toolbar. The tutorial reads 

"Colorify trashbin/recycle buttons on tiddler toolbar

The __below__ tiddler sets the style for trashbin and restore buttons on tiddler view/edit toolbars. By default it is disabled, to enable it, simply

    open the tiddler and tag it with $:/tags/Stylesheet
    edit it to your taste

Customize the trashed item view

The __below__ tiddler define the styles for tiddlers act as container for trashed items when opened in story river (view mode), simply edit it to meet your requirements"

but the "below" tiddler is not specified. Am I missing something? I know I can just create a tiddler and tag it with $:/tags/Stylesheet but the instructions aren't very clear on what a novice, first time user of the plugin or TW would need to do....i.e. create a tiddler and tag it....the instructions read like there should be a tiddler already existing. I am happy to update the documentation and make the changes if you want. Would i have to issue a "pull request" on the repo? I'm learning my way around Github as well as TW. 

Regards,

Declan

**Comment by dhjackal** [comment]
Also, it might be helpful to put some sample CSS code into the instructions so that users have an idea of what they can possibly change. I write this very much from a user prespective.

**Comment by dhjackal** [comment]
I

**Comment by dhjackal** [comment]
Pull request issued

**Comment by kookma** [comment]
Hi Declan,
 Please see the updated doc.
 There was an error in doc.

**Comment by dhjackal** [comment]
Hi Mohammad, 

Updated document looks good. Nice one.
