### ISSUE TITLE
[feature request] navigate to tiddler when restored

### ISSUE THREAD

**Issue by hchaase** [kookma/TW-Trashbin#5]
navigate to tiddler when restored. That would be expected behaviour I think. 
I tried to do it in` $:/plugins/kookma/trashbin/macros/restore`  but again I dont know how to remove the prefix.

`<$action-navigate $to="[<currentTiddler>removeprefix[$:/trashbin/]]"/>`

**Comment by kookma** [comment]
There are three points where you have restore button

1. in trashbin sidebar tab in front of each individual tiddler
2. in trashbin sidebar tab in restore all tab
3. in toolbar of an individual trashed tiddler

I think this make sense for case 3! What do you think?

**Comment by kookma** [comment]
> `<$action-navigate $to="[<currentTiddler>removeprefix[$:/trashbin/]]"/>`
This is correct and should be placed after restore!

**Comment by hchaase** [comment]
yes definitely case 3 
could also be relevant for 1 I would think. But as the modified date gets updated they will  be at top in the recent tab, however I think it would be a better experience if you navigate to them in the story river (for 1).

**Comment by kookma** [comment]
Okay, thank you! I will work on that to see how I can implement!

**Comment by kookma** [comment]
Done! See release 1.1.0
