### ISSUE TITLE
Feature request:  Sort by time trashed

### ISSUE THREAD

**Issue by hchaase** [kookma/TW-Trashbin#6]
In the trash bin tabs, sort tiddlers by time trashed (maybe modified?). 

If you have a couple of trashed itmes and you trash a tiddler by accident, and want it back, it takes time searching through titles. it would be much easier if it was sorted my time trashed.

But then again, if you are looking to find something you trashed some time ago but can't remember when, it will be equally cumbersome. Maybe I should empty my trash more often :)

**Comment by kookma** [comment]
@hchaase 
Thank you. This is a feature request. I will add this!

**Comment by hchaase** [comment]
Thanks

Hope you are well in this pandemic

fre. d. 20. mar. 2020 18.41 skrev Mohammad Rahmani <notifications@github.com

**Comment by kookma** [comment]
Thank you! 
Take care.

**Comment by kookma** [comment]
Done! See this in release 1.1.0
